###########
# site.title

title:
  en: 'Wolfgang Deutsch'
  de: 'Wolfgang Deutsch'
subtitle:
  en: 'Software Developer. Some extras included.'
  de: 'Software Entwickler. Mit ein paar Extras'

nav:
  en:
    - { title: 'Home', href: '/' }
    - { title: 'Services', href: '/services' }
    - { title: 'Social', href: '/social'}
    - { title: 'Blog', href: '/blog'}
    - { title: 'Contact', href: '/contact' }
  de:
    - { title: 'Start', href: '/index_de' }
    - { title: 'Leistungen', href: '/leistungen' }
    - { title: 'Social', href: '/social_de'}
    - { title: 'Blog', href: '/blog_de'}
    - { title: 'Kontakt', href: '/kontakt' }

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md

include: ['_pages']
permalink: /[page]/
