###########
# site.title

title:
  en: 'Wolfgang Deutsch'
  de: 'Wolfgang Deutsch'
subtitle:
  en: 'Software Developer. Some extras included.'
  de: 'Software Entwickler. Mit ein paar Extras'

nav:
  en:
    - { title: 'Home', href_base: '' }
    - { title: 'Services', href_base: 'services' }
    - { title: 'Social', href_base: 'social'}
    - { title: 'Blog', href_base: 'blog'}
    - { title: 'Contact', href_base: 'contact' }
  de:
    - { title: 'Start', href_base: 'index' }
    - { title: 'Leistungen', href_base: 'services' }
    - { title: 'Social', href_base: 'social'}
    - { title: 'Blog', href_base: 'blog'}
    - { title: 'Kontakt', href_base: 'contact' }

service_colors:
  code:
    header: "#303030"
    column: "#383838"
  operation:
    header: "#404040"
    column: "#484848"
  coaching:
    header: "#505050"
    column: "#585858"
  consulting:
    header: "#606060"
    column: "#686868"

services:
  en:
    - name: Code
      id: code
      sections:
        - { name: 'Backend systems', href_base: 'backend_systems' }
        - { name: 'Code cleanup', href_base: 'code_cleanup' }
        - { name: 'Code rewrite', href_base: 'code_rewrite' }
        - { name: 'Continuous Integration', href_base: 'continous_integration'}
        - { name: 'Automation', href_base: 'automation'}
    - name: Operation
      id: operation
      sections:
        - { name: 'Deployment', href_base: 'deployment'}
        - { name: 'Monitoring', href_base: 'monitoring'}
        - { name: 'Cloud', href_base: 'cloud'}
        - { name: 'Systems Lifecycle', href_base: 'systems_lifecycle'}
        - { name: 'Change management', href_base: 'change_management'}
    - name: Coaching
      id: coaching
      sections:
        - { name: 'Test Driven Development', href_base: 'tdd' }
        - { name: 'Refactoring', href_base: 'refactoring' }
        - { name: 'Clean Code', href_base: 'clean_code' }
        - { name: 'Agile Development', href_base: 'agile_development' }
        - { name: 'Scalability', href_base: 'scalability' }
    - name: Consulting
      id: consulting
      sections:
        - { name: 'Budgeting', href_base: 'budgeting'}
        - { name: 'Tools Evaluation', href_base: 'tools_evaluation'}
        - { name: 'Code Review', href_base: 'code_review'}
        - { name: 'Automation', href_base: 'automation'}
  de:
    - name: Code
      id: code
      sections:
        - { name: 'Backend Systeme', href_base: 'backend_systems' }
        - { name: 'Code Bereinigung', href_base: 'code_cleanup' }
        - { name: 'Code Erneuerung', href_base: 'code_rewrite' }
        - { name: 'Continuous Integration', href_base: 'continous_integration'}
        - { name: 'Automatisierung', href_base: 'automation'}
    - name: Operation
      id: operation
      sections:
        - { name: 'Deployment', href_base: 'deployment'}
        - { name: 'Monitoring', href_base: 'monitoring'}
        - { name: 'Cloud', href_base: 'cloud'}
        - { name: 'System Lebenszyklus', href_base: 'systems_lifecycle'}
        - { name: 'Änderungs management', href_base: 'change_management'}
    - name: Coaching
      id: coaching
      sections:
        - { name: 'Test Driven Development', href_base: 'tdd' }
        - { name: 'Refactoring', href_base: 'refactoring' }
        - { name: 'Clean Code', href_base: 'clean_code' }
        - { name: 'Skalierbarkeit', href_base: 'scalability' }
        - { name: 'Agile Entwicklung', href_base: 'agile_development' }
    - name: Consulting
      id: consulting
      sections:
        - { name: 'Budgetierung', href_base: 'budgeting'}
        - { name: 'Tools Evaluation', href_base: 'tools_evaluation'}
        - { name: 'Code Review', href_base: 'code_review'}
        - { name: 'Automation', href_base: 'automation'}


markdown: kramdown
sass:
  sass_dir: css
  style:    expanded
exclude:
- README.md
- LICENSE.md
include: ['_pages']
