###########
# site.title

contact:
  - name: Email
    link: mailto:wolfgang@wolfgangdeutsch.work
    link-text: "wolfgang at wolfgangdeutsch dot work"
  - name: Facebook
    link: https://www.facebook.com/wolfgangdeutsch.work
    link-text: "@wolfgangdeutsch.work"
  - name: Twitter
    link: https://twitter.com/wolfgangwork
    link-text: "@wolfgangwork"

strings:
  under_construction_msg:
    en: 'Site under construction'
    de: 'Webseite im Aufbau'
  language:
    en: 'English'
    de: 'Deutsch'
  site_title:
    en: 'Wolfgang Deutsch•Work'
    de: 'Wolfgang Deutsch•Work'

nav:
  en:
    - { title: 'Home', href_base: '', ref: 'home' }
    - { title: 'Services', href_base: 'services' }
    - { title: 'Contact', href_base: 'contact' }
  de:
    - { title: 'Start', href_base: 'index', ref: 'home' }
    - { title: 'Leistungen', href_base: 'services' }
    - { title: 'Kontakt', href_base: 'contact' }

services:
  languages:
    en:
      - name: Backends
        id: backends
        sections:
          - Code # extend, cleaup, rewrite, maintain
          - Architecture # networking, storage, scaling
          - Automation
          - Tooling
          - Legacy Code
      - name: DevOps
        id: devops
        sections:
          - Operation
          - Load Testing
          - Monitoring
          - Scaling
      - name: Coaching
        id: coaching
        sections:
          - Backends
          - DevOps
          - Test Driven Development
          - Agile Planning
      - name: Consulting
        id: consulting
        sections:
          - Feasibility
          - Systems Evaluation
          - Due Diligence
    de:
      - name: Backends
        id: backends
        sections:
          - Code
          - Architektur
          - Automatisierung
          - Werkzeuge
          - Legacy Code
      - name: DevOps
        id: devops
        sections:
          - Betreibung
          - Last Tests
          - Überwachung
          - Skalierung
      - name: Coaching
        id: coaching
        sections:
          - Backends
          - DevOps
          - Test Driven Development
          - Agile Planung
      - name: Consulting
        id: consulting
        sections:
          - Machbarkeit
          - System-Auswertung
          - Due Diligence
  links:
    backends:
      - code
      - architecture
      - automation
      - tooling
      - legacy_code
    devops:
      - operation
      - load_testing
      - monitoring
      - scaling
    coaching:
      - backends
      - devops
      - tdd
      - agile_planning
    consulting:
      - feasibility
      - systems_evaluation
      - due_diligence

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
  - README.md
  - LICENSE.md
include: ['_pages']

google_analytics: UA-103674705-1
