###########
# site.title

strings:
  under_construction_msg:
    en: 'Site under construction'
    de: 'Webseite im Aufbau'
  language:
    en: 'English'
    de: 'Deutsch'
  site_title:
    en: 'Wolfgang Deutsch•Work'
    de: 'Wolfgang Deutsch•Work'

nav:
  en:
    - { title: 'Home', href_base: '', ref: 'home' }
    - { title: 'Services', href_base: 'services' }
    - { title: 'Contact', href_base: 'contact' }
  de:
    - { title: 'Start', href_base: 'index', ref: 'home' }
    - { title: 'Leistungen', href_base: 'services' }
    - { title: 'Kontakt', href_base: 'contact' }

services:
  languages:
    en:
      - name: Programming
        id: code
        sections:
          - New Systems
          - Existing Systems # extend, cleaup, rewrite, maintain
          - Legacy Code
          - Tooling # Automation for all kinds of things, but also GUI tools, etc
      - name: DevOps
        id: devops
        sections:
          - Deployment # includes dev/stage/live
          - Load Testing
          - Scaling
          - Monitoring
          - Networking
      - name: Coaching
        id: coaching
        sections:
          - Test Driven Development
          - Refactoring
          - Clean Code
          - DevOps
          - Agile Planning
      - name: Consulting
        id: consulting
        sections:
          - Feasibility
          - Systems Evaluation
          - Code Review
          - Vendor Selection
          - Scalability
    de:
      - name: Programmierung
        id: code
        sections:
          - Neue Systeme
          - Bestehende Systeme # extend, cleaup, rewrite, maintain
          - Legacy Code
          - Werkzeuge
      - name: DevOps
        id: devops
        sections:
          - Deployment # includes dev/stage/live
          - Last Tests
          - Skalierung
          - Überwachung
          - Vernetzung
      - name: Coaching
        id: coaching
        sections:
          - Test Driven Development
          - Refactoring
          - Clean Code
          - DevOps
          - Agile Planung
      - name: Consulting
        id: consulting
        sections:
          - Machbarkeit
          - System-Auswertung
          - Code Review
          - Anbieter Auswahl
          - Skalierbarkeit
  links:
    code:
      - new_systems
      - existing_systems
      - legacy_code
      - tooling
    devops:
      - deployment
      - load_testing
      - scaling
      - monitoring
      - networking
    coaching:
      - tdd
      - refactoring
      - clean_code
      - agile_planning
      - developer_tools
    consulting:
      - feasibility
      - devops
      - systems_evaluation
      - code_review
      - vendor_selection
      - scalability

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
  - README.md
  - LICENSE.md
include: ['_pages']

google_analytics: UA-103674705-1
