###########
# site.title


title:
  en: 'Wolfgang Deutsch'
  de: 'Wolfgang Deutsch'
subtitle:
  en: 'Software Developer. Some extras included.'
  de: 'Software Entwickler. Mit ein paar Extras'

nav:
  en:
    - { title: 'Home', href: '/' }
    - { title: 'Services', href: '/services.html' }
    - { title: 'Social', href: '/social.html'}
    - { title: 'Blog', href: '/blog.html'}
    - { title: 'Contact', href: '/contact.html' }
  de:
    - { title: 'Start', href: '/' }
    - { title: 'Leistungen', href: '/leistungen.html' }
    - { title: 'Social', href: '/social_de.html'}
    - { title: 'Blog', href: '/blog_de.html'}
    - { title: 'Kontakt', href: '/kontakt.html' }


#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md
