###########
# site.title

title:    'Wolfgang Deutsch'
subtitle: 'Software Developer. Some extras included.'


nav:
- { title: 'Home',                 href: '/' }
- { title: 'Services',             href: '/services.html' }
- { title: 'Social', href: '/social.html'}
- { title: 'Blog', href: '/blog.html'}
- { title: 'Contact', href: '/contact.html' }


#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md
