###########
# site.title

title:
  en: 'Wolfgang Deutsch dot(h) Work'
  de: 'Wolfgang Deutsch dot(h) Work'
subtitle:
  en: 'Backend Developer. Some extras included.'
  de: 'Backend Entwickler. Mit ein paar Extras'

nav:
  en:
    - { title: 'Home', href_base: '' }
    - { title: 'Services', href_base: 'services' }
    - { title: 'Social', href_base: 'social'}
    - { title: 'Blog', href_base: 'blog'}
    - { title: 'Contact', href_base: 'contact' }
  de:
    - { title: 'Start', href_base: 'index' }
    - { title: 'Leistungen', href_base: 'services' }
    - { title: 'Social', href_base: 'social'}
    - { title: 'Blog', href_base: 'blog'}
    - { title: 'Kontakt', href_base: 'contact' }

services:
  languages:
    en:
      - name: Programming
        id: code
        sections:
          - New Systems
          - Existing Systems # extend, cleaup, rewrite, maintain
          - Legacy Code
          - Automation
          - Tools
      - name: DevOps
        id: operation
        sections:
          - Deployment
          - Release Management
          - Monitoring
          - Scaling
          - Load Testing
          - Networking
      - name: Coaching
        id: coaching
        sections:
          - Test Driven Development
          - Refactoring
          - Clean Code
          - Agile Planning
      - name: Consulting
        id: consulting
        sections:
          - DevOps
          - Feasibility
          - Systems Evaluation
          - Tools Evaluation
          - Scalability
    de:
      - name: Programmierung
        id: code
        sections:
          - Code Bereinigung
          - Code Erneuerung
          - Continuous Integration
          - Automatisierung
      - name: DevOps
        id: operation
        sections:
          - Deployment
          - Monitoring
          - Cloud
          - System Lebenszyklus
          - Änderungs management
      - name: Coaching
        id: coaching
        sections:
          - Test Driven Development
          - Refactoring
          - Clean Code
          - Skalierbarkeit
          - Agile Entwicklung
      - name: Consulting
        id: consulting
        sections:
          - Budgetierung
          - Tools Evaluation
          - Code Review
          - Automation
  links:
    code:
      - code_cleanup
      - code_rewrite
      - continous_integration
      - automation
    operation:
      - deployment
      - monitoring
      - cloud
      - systems_lifecycle
      - change_management
    coaching:
      - tdd
      - refactoring
      - clean_code
      - agile_development
      - scalability
    consulting:
      - budgeting
      - tools_evaluation
      - code_review
      - automation


markdown: kramdown
sass:
  sass_dir: css
  style:    expanded
exclude:
- README.md
- LICENSE.md
include: ['_pages']
