###########
# site.title

title:
  en: 'Wolfgang Deutsch'
  de: 'Wolfgang Deutsch'
subtitle:
  en: 'Software Developer. Some extras included.'
  de: 'Software Entwickler. Mit ein paar Extras'

nav:
  en:
    - { title: 'Home', href_base: '' }
    - { title: 'Services', href_base: 'services' }
    - { title: 'Social', href_base: 'social'}
    - { title: 'Blog', href_base: 'blog'}
    - { title: 'Contact', href_base: 'contact' }
  de:
    - { title: 'Start', href_base: 'index_de' }
    - { title: 'Leistungen', href_base: 'leistungen' }
    - { title: 'Social', href_base: 'social_de'}
    - { title: 'Blog', href_base: 'blog_de'}
    - { title: 'Kontakt', href_base: 'kontakt' }

# * **Code**
#   * Backend systems
#   * Code cleanup
#   * Code rewrite
#   * Automation
# * **Operation**
#   * Deployment
#   * Monitoring
#   * Cloud/Serverless computing
#   * Systems Lifecycle
#   * Continuous Integration
#   * Change management
# * **Coaching**
# * **Consulting**
# * **Leadership**


services:
  en:
    - name: Code
      id: code
      sections:
        - { name: 'Backend systems', href_base: 'backend_systems' }
        - { name: 'Code cleanup', href_base: 'code_cleanup' }
        - { name: 'Code rewrite', href_base: 'code_rewrite' }
        - { name: 'Automation', href_base: 'automation'}
    - name: Operation
      id: operation
      sections:
        - { name: 'Deployment', href_base: 'deployment'}
        - { name: 'Monitoring', href_base: 'monitoring'}
        - { name: 'Cloud', href_base: 'cloud'}
        - { name: 'Systems Lifecylcle', href_base: 'systems_lifecycle'}
        - { name: 'Continuous Integration', href_base: 'continous_integration'}
        - { name: 'Change management', href_base: 'change_management'}
    - name: Coaching
      id: coaching
      sections:
        - { name: 'Test Driven Development', href_base: 'tdd' }
        - { name: 'Refactoring', href_base: 'refactoring' }
        - { name: 'Clean Code', href_base: 'clean_code' }
        - { name: 'Scalability', href_base: 'scalability' }
        - { name: 'Agile Development', href_base: 'agile_development' }
        - { name: 'Clean Code', href_base: 'clean_code' }
    - name: Consulting
    - name: Leadership
  de:
    - name: Code
      id: code
      sections:
        - { name: 'Backend Systeme', href_base: 'backend_systems' }
        - { name: 'Code Bereinigung', href_base: 'code_cleanup' }
        - { name: 'Code Erneuerung', href_base: 'code_rewrite' }
        - { name: 'Automatisierung', href_base: 'automation'}
    - name: Operation
      id: operation
      sections:
        - { name: 'Deployment', href_base: 'deployment'}
        - { name: 'Monitoring', href_base: 'monitoring'}
        - { name: 'Cloud', href_base: 'cloud'}
        - { name: 'System Lebenszyklus', href_base: 'systems_lifecycle'}
        - { name: 'Continuous Integration', href_base: 'continous_integration'}
        - { name: 'Änderungs management', href_base: 'change_management'}
    - name: Coaching
      id: coaching
      sections:
        - { name: 'Test Driven Development', href_base: 'tdd' }
        - { name: 'Refactoring', href_base: 'refactoring' }
        - { name: 'Clean Code', href_base: 'clean_code' }
        - { name: 'Skalierbarkeit', href_base: 'scalability' }
        - { name: 'Agile Entwicklung', href_base: 'agile_development' }
    - name: Consulting
    - name: Leadership

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
- LICENSE.md

include: ['_pages']
permalink: /[page]/
