###########
# site.title

title:
  en: 'Wolfgang Deutsch•Work'
  de: 'Wolfgang Deutsch•Work'
subtitle:
  en: 'Backend Developer. Some extras included.'
  de: 'Backend Entwickler. Mit ein paar Extras'

languages:
  en: 'English'
  de: 'Deutsch'
nav:
  en:
    - { title: 'Home', href_base: '', ref: 'home' }
    - { title: 'Services', href_base: 'services' }
    - { title: 'Social', href_base: 'social'}
    - { title: 'Blog', href_base: 'blog'}
    - { title: 'Contact', href_base: 'contact' }
  de:
    - { title: 'Start', href_base: 'index', ref: 'home' }
    - { title: 'Leistungen', href_base: 'services' }
    - { title: 'Social', href_base: 'social'}
    - { title: 'Blog', href_base: 'blog'}
    - { title: 'Kontakt', href_base: 'contact' }

services:
  languages:
    en:
      - name: Programming
        id: code
        sections:
          - New Systems
          - Existing Systems # extend, cleaup, rewrite, maintain
          - Legacy Code
          - Automation
          - Tools
      - name: DevOps
        id: operation
        sections:
          - Deployment # includes dev/stage/live
          - Load Testing
          - Scaling
          - Monitoring
          - Networking
      - name: Coaching
        id: coaching
        sections:
          - Test Driven Development
          - Refactoring
          - Clean Code
          - Agile Planning
          - Developer Tools
      - name: Consulting
        id: consulting
        sections:
          - Feasibility
          - DevOps
          - Systems Evaluation
          - Code Review
          - Vendor Choice
          - Scalability
    de:
      - name: Programmierung
        id: code
        sections:
          - Neue Systeme
          - Bestehende Systeme # extend, cleaup, rewrite, maintain
          - Legacy Code
          - Automatisierung
          - Tools
      - name: DevOps
        id: operation
        sections:
          - Deployment # includes dev/stage/live
          - Last Tests
          - Skalierung
          - Monitoring
          - Networking
      - name: Coaching
        id: coaching
        sections:
          - Test Driven Development
          - Refactoring
          - Clean Code
          - Agile Planung
          - Entwickler Tools
      - name: Consulting
        id: consulting
        sections:
          - Machbarkeit
          - DevOps
          - System Bewertung
          - Code Review
          - Anbieter Auswahl
          - Skalierbarkeit
  links:
    code:
      - new_systems
      - code_cleanup
      - code_rewrite
      - continous_integration
      - automation
    operation:
      - deployment
      - monitoring
      - cloud
      - systems_lifecycle
      - change_management
    coaching:
      - tdd
      - refactoring
      - clean_code
      - agile_development
      - scalability
    consulting:
      - budgeting
      - tools_evaluation
      - code_review
      - automation


markdown: kramdown
sass:
  sass_dir: css
  style:    expanded
exclude:
- README.md
- LICENSE.md
include: ['_pages']
